name: LRA-FORMATTING

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:
    types: [ opened, edited, synchronize, ready_for_review, labeled, unlabeled, reopened ]

jobs:
  verify-format:
    name: Verify format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v5
        with:
          java-version: 17 # minimum supported JDK

      - name: Verify pull request format
        run: ./mvnw formatter:validate
